### ISSUE TITLE
🔹 - Notifications Platform / Data Layer (MVP)

### ISSUE THREAD

**Issue by thisisjoshford** [near/Pagoda-Roadmap#1]
```[tasklist]
### Tasks
- [ ] https://github.com/near/github-test/issues/2
- [ ] https://github.com/near/github-test/issues/4
- [ ] https://github.com/near/github-test/issues/3
- [ ] this
```
