### ISSUE TITLE
🔰 [Initiative] BOS web engine

### ISSUE THREAD

**Issue by near-arthur** [near/Pagoda-Roadmap#13]
### Description
BOS utilizes a virtual machine to render front-end components from source code stored on-chain called [Near Social VM](https://github.com/NearSocial/VM). Feedback from developers building on BOS highlights some critical limitations that hamper integrating classic frameworks and tools (e.g., React Components and npm libraries). 

The [BOS Web Engine R&D Project](https://github.com/near/bos-web-engine) explores the creation of a new rendering + execution layer that will enable a component development experience similar to vanilla React. 

---

### Goals

MVP:
- [ ] Feature parity with current NEAR Social VM
- [ ] Support `npm` dependencies
- [ ] component code is minimally different from vanilla React
- [ ] isolation of component execution leverages browser sandboxing (iframes)
- [ ] configurable trust model to tune performance when embedded components have been vetted

Stretch:
- [ ] TypeScript support
- [ ] Full web API support (canvas, etc)
- [ ] Cross-component global state management

---

### Resources
 👉 [Solution Architecture](https://github.com/near/bos-web-engine/blob/main/architecture.md)
 
 ---

### Tracking
👉 [Roadmap](https://github.com/orgs/near/projects/92/views/7?sliceBy%5Bvalue%5D=near%2Fbos-web-engine)
👉 [Sprint Planning](https://github.com/orgs/near/projects/92/views/6?sliceBy%5Bvalue%5D=near%2Fbos-web-engine)
👉 [Related EPICS](https://github.com/near/bos-web-engine/issues?q=is:open+is:issue+label:Epic)

```[tasklist]
### MVP
```

```[tasklist]
### Stretch Goals
```

**Comment by Tarnadas** [comment]
I would have loved to not put the focus on being compatible with React, but rather with open web standards.
My idea is that Near Social VM v2 should support Web Components.

This would give BOS component developers the freedom to choose their framework. I know that Angular and Svelte can compile to Web Components and I'd assume it's also possible with React and Vue. The used npm libraries are probably also bundled inside the BOS component.

Have you already considered Web Components?

**Comment by thisisjoshford** [comment]
> I would have loved to not put the focus on being compatible with React, but rather with open web standards. My idea is that Near Social VM v2 should support Web Components.
> 
> This would give BOS component developers the freedom to choose their framework. I know that Angular and Svelte can compile to Web Components and I'd assume it's also possible with React and Vue. The used npm libraries are probably also bundled inside the BOS component.
> 
> Have you already considered Web Components?

Hey @Tarnadas ! Thanks so much for the feedback here! Would you mind posting this as [a discussion on the BOS Web Engine repo ](https://github.com/near/bos-web-engine/discussions)and we can continue this conversation there?

**Comment by thisisjoshford** [comment]
BWE Project deprecated. See blogpost on docs for more info -> https://docs.near.org/blog/bos-web-engine-sunset
