### ISSUE TITLE
🔰 [Initiative] Data Lakehouse Maintenance, Cost, Optimizations

### ISSUE THREAD

**Issue by eduohe** [near/Pagoda-Roadmap#140]
```[tasklist]
### Tasks
- [ ] https://github.com/near/near-databricks-lakehouse/issues/3
- [ ] https://github.com/near/near-databricks-lakehouse/issues/4
- [ ] https://github.com/near/near-databricks-lakehouse/issues/5
- [ ] https://github.com/near/near-databricks-lakehouse/issues/6
- [ ] https://github.com/near/near-databricks-lakehouse/issues/7
- [ ] https://github.com/near/near-databricks-lakehouse/issues/8
- [ ] https://github.com/near/near-databricks-lakehouse/issues/9
- [ ] https://github.com/near/near-databricks-lakehouse/issues/10
- [ ] https://github.com/near/near-databricks-lakehouse/issues/11
- [ ] https://github.com/near/near-databricks-lakehouse/issues/19
- [ ] https://github.com/near/near-public-lakehouse/issues/14
- [ ] https://github.com/near/near-public-lakehouse/issues/15
- [ ] https://github.com/near/near-public-lakehouse/issues/16
- [ ] https://github.com/near/Pagoda-Roadmap/issues/151
```
