### ISSUE TITLE
🔰 [Initiative] NEARCon App Quest

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/Pagoda-Roadmap#148]
### Description
Event: Explore apps on BOS and decide what NEARians should first see in the next three months on the featured section at  App Library

**User Flow(post discussion with eng on cutting down scope)**
Developer: 
1. Become eligible when dApp owners fill in their descriptions of Apps + tags selected that contains (Earn, Play, Develop, Engage) in Metadata field 
2. Promote you dApps!

Users: 
1. Scan QR code available at NEARCon to visit App Library and explore registered apps
2. Send Likes to the app you think (ideally, checking feasbility)

End Result:
1. Leaderboard will be released with impression data + likes
2. Feature section in App Library will be featuring the winners

### Goal
- Incentivize more visits and interactions of the dApp
- Kick off Feedback loop to gather more usage data and display it on App Library later to improve signaling on BOS

### Resources
(Relevant documentation, Figma links, and other reference material)
- [Design](https://www.figma.com/proto/ElMQPaioe8XOfaHEdCCmLf/Discovery?page-id=748%3A23610&type=design&node-id=748-25605&viewport=639%2C201%2C0.5&t=8XNhioITpszeBVCG-1&scaling=min-zoom)
- [Experiment Product Ideation Document](https://docs.google.com/document/d/16uQdR0iRcWq8kyBFgUauATdWq7HMPQYMiNZyPnPkG9o/edit#heading=h.6ly78vgpa9yr) 
- [Like button on Posts](https://github.com/near/near-discovery-components/blob/develop/src/LikeButton.jsx)
- [Activity Page/home page landing](https://near.org/near/widget/ComponentDetailsPage?src=near/widget/ActivityPage) 
- [BOS All Star with similar system](https://near.org/near/widget/ComponentDetailsPage?src=hack.near/widget/widgets.rank&tab=source)

```[tasklist]
### Related Epics
- [ ] https://github.com/near/data-platform/issues/33
- [ ] https://github.com/near/data-platform/issues/32
- [ ] https://github.com/near/data-platform/issues/29
- [ ] https://github.com/near/data-platform/issues/30
- [ ] https://github.com/near/data-platform/issues/31
```
