### ISSUE TITLE
🔰 [Initiative] QueryAPI General Availability

### ISSUE THREAD

**Issue by pkudinov** [near/Pagoda-Roadmap#149]
QueryAPI users have to be whitelisted to use QueryAPI right now. We would like to remove this limitation and make it open for anyone to build an indexer.

Things to consider:

- Database scalability: horizontal scaling per indexer, vertical scaling, read replicas
- Registry smart contract: pay for storage, remove whitelist
- Performance testing on heavy indexers
- Automatically shut down indexers with unused APIs

```[tasklist]
### Tasks
- [ ] https://github.com/near/queryapi/issues/396
- [ ] https://github.com/near/queryapi/issues/300
- [ ] https://github.com/near/queryapi/issues/213
- [ ] https://github.com/near/queryapi/issues/214
- [ ] https://github.com/near/queryapi/issues/198
```
