### ISSUE TITLE
🔰 [Initiative] FastAuth continued development

### ISSUE THREAD

**Issue by near-arthur** [near/Pagoda-Roadmap#15]
```[tasklist]
### Related Epics
- [ ] https://github.com/near/mpc-recovery/issues/296
- [ ] https://github.com/near/mpc-recovery/issues/281
- [ ] https://github.com/near/fast-auth-signer/issues/48
- [ ] https://github.com/near/mpc-recovery/issues/242
- [ ] https://github.com/near/fast-auth-signer/issues/26
```
