### ISSUE TITLE
🔰 [Initiative] Expand content moderation framework

### ISSUE THREAD

**Issue by near-arthur** [near/Pagoda-Roadmap#18]
Strategic Document:https://pagodaplatform.atlassian.net/wiki/spaces/SITS/pages/289701958/Product+Hypothesis+-+Content+Moderation 

Summary: The content moderation feature is designed to benefit all users who participate in http://near.org/ by keeping the community safe, inclusive and respectful community-driven environment.
![Image](https://github.com/near/Pagoda-Roadmap/assets/5955639/211abe91-ca84-44c0-bc88-4ae55a636a29)

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/390
- [ ] https://github.com/near/near-discovery/issues/406
- [ ] https://github.com/near/near-discovery/issues/433
- [ ] https://github.com/near/near-discovery/issues/453
- [ ] https://github.com/near/near-discovery/issues/469
- [ ] https://github.com/near/near-discovery/issues/499
- [ ] https://github.com/near/near-discovery/issues/510
```
