### ISSUE TITLE
🔰 [Initiative] Near.org Website Redesign

### ISSUE THREAD

**Issue by near-arthur** [near/Pagoda-Roadmap#22]
Description

This effort is a revamp of the near.org website landing pages and main navigation.

[Figma](https://www.figma.com/file/50VvVImqAoHAhJctYdPBzv/%F0%9F%9B%A0%EF%B8%8F-Near.org---v2.2023?type=design&node-id=1014-33426&mode=design&t=9sTMk8uDrKYRzWSy-0)

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/424
- [ ] https://github.com/near/near-discovery/issues/416
- [ ] https://github.com/near/near-discovery-components/issues/360
- [ ] https://github.com/near/near-discovery-components/issues/361
- [ ] https://github.com/near/near-discovery-components/issues/362
- [ ] https://github.com/near/near-discovery/issues/626
- [ ] https://github.com/near/near-discovery-components/issues/364
- [ ] https://github.com/near/near-discovery/issues/663
- [ ] https://github.com/near/near-discovery/issues/708
- [ ] https://github.com/near/near-discovery/issues/697
```
