### ISSUE TITLE
🔰 [Initiative] Push Notifications v1

### ISSUE THREAD

**Issue by near-arthur** [near/Pagoda-Roadmap#23]
```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/533
- [ ] https://github.com/near/near-discovery/issues/534
- [ ] https://github.com/near/near-discovery/issues/535
- [ ] https://github.com/near/near-discovery/issues/536
- [ ] https://github.com/near/docs/issues/1504
- [ ] https://github.com/near/near-discovery/issues/537
- [ ] https://github.com/near/near-discovery/issues/542
- [ ] https://github.com/near/near-discovery/issues/621
- [ ] https://github.com/near/near-discovery/issues/540
```

**Comment by Tarnadas** [comment]
Any chance that custom notifications will be added?
Idk if "notificationText" (https://github.com/near/near-discovery/blob/develop/public/service-worker.js#L80) already has all necessary information.

A custom notification on the social.near contract that I send and is properly rendered on near.org, but doesn't send a push notification is e.g. this one:
https://nearblocks.io/txns/9WMvWm9sE9yPBZmgKET2Pyk9Aj57rj5tq1aCMdQ8CZGu#execution
You also see the "poke" that I additionally send as a workaround.
