### ISSUE TITLE
🔰 [Initiative] Decentralized & secure identity solution

### ISSUE THREAD

**Issue by near-arthur** [near/Pagoda-Roadmap#24]
https://docs.google.com/document/d/1rc4F7U9xp_G5K2_8wX-4M9dWBrOPtoB5lWLlOty9rEw/edit#

[Integrating with Fractal's iDOS](https://fractal.notion.site/idOS-NEAR-integration-handbook-895b3a15084547a9aa6ebec55c76364a)

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/557
- [ ] https://github.com/near/near-discovery/issues/555
- [ ] https://github.com/near/near-discovery/issues/560
```

**Comment by charleslavon** [comment]
@Ishatt @tidus974 I've closed this as complete since [560](https://github.com/near/near-discovery/issues/560) is not related to fractal. Feel to re-open if you feel it's helpful.
