### ISSUE TITLE
🔰 [Initiative] Privacy & legal compliance product and processes

### ISSUE THREAD

**Issue by near-arthur** [near/Pagoda-Roadmap#26]
[Producthttps://docs.google.com/document/d/1dSdnw_T22v2wnTHGXU47HwQhSa2RRV5VM8QP6Xy2GSk/edit#heading=h.oijkma6hzk4r](https://docs.google.com/document/d/1dSdnw_T22v2wnTHGXU47HwQhSa2RRV5VM8QP6Xy2GSk/edit#heading=h.oijkma6hzk4r)
```[tasklist]
### Epics
- [ ] https://github.com/near/near-discovery/issues/518
- [ ] https://github.com/near/near-discovery/issues/519
- [ ] https://github.com/near/near-discovery/issues/520
- [ ] https://github.com/near/near-discovery/issues/521
- [ ] https://github.com/near/near-discovery/issues/580
```

**Comment by charleslavon** [comment]
@Ishatt can this be closed?

**Comment by tidus974** [comment]
Hi team, I am re-opening this here since some of the epics on the user request and dashboard are still pending. Thanks!
