### ISSUE TITLE
Push notifications server

### ISSUE THREAD

**Issue by thisisjoshford** [near/Pagoda-Roadmap#3]
**EPIC:** #1 Notifications Platform

**Objective:** Create an awsome push notification server!

```[tasklist]
### Sub-Tasks
- [ ] Do this thing
- [ ] Do that thing
- [ ] Do the final thing
```
