### ISSUE TITLE
🔹 - Desktop Web Notifications

### ISSUE THREAD

**Issue by thisisjoshford** [near/Pagoda-Roadmap#5]
```[tasklist]
### Tasks
- [ ] https://github.com/near/github-test/issues/6
- [ ] https://github.com/near/github-test/issues/7
- [ ] https://github.com/near/github-test/issues/4
```
