### ISSUE TITLE
🔰 [Initiative] Component Search Data Enrichment + Intuitive Component Display

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/Pagoda-Roadmap#64]
### Description
This initiative is aiming to improve component Search with richer data + intuitive display and view
![Image](https://github.com/near/Pagoda-Roadmap/assets/35774078/9dd14b0a-6e6d-479a-a45f-7be6ff4f398b)

### User Flow
1. A developer is looking to find a pagination component and search for "pagination" in the search bar (this should be doable from the search bar on top + command palette search + search bar within the sandbox)
2. A developer land on a search result page with the component filter; It has the list of components on the left and a snapshot of the component loaded on the right with some more information about the component 
3. The details page include following information about the component
> - Description, tags and other metadata of the component
> - Number of times this component is forked
> - Number of times this component is used in other components
> - Number of times this component is loaded across BOS
> - Number of times there is render errors
> - Ability to preview the component
> - A list of parent component(with links to open these components) where this component is used in
> - Information about the creator of this component (number of days they are active, reputation score calculated from data such as num of components published/forked/used, lines of code, number of likes/save received etc.)
> - <Dev Data MVP Req: Total Components Published; Total Components Forkek; Time joined> 
> - Number of likes and bookmark this component has received (when available)
4. The developer also sees options to view source code, historical updates made to the component and a discussion section of the component in the opened page
5. After careful examination, the developer decide to fork the component they find most suitable for their needs

**Question to consider**
- What would the experience look like if the component renders into blank? (this could happen to components that are embedded in some frames or code; or logic components such as the ones for "infinite scroll" etc.)

**Dependencies**
- Developer Reputation System as additional data to rank components

### Resources
(Relevant documentation, Figma links, and other reference material)
- [Design WIP](https://www.figma.com/file/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?type=design&node-id=902-5087&mode=design&t=bZXM6DZmHEX12PWg-0) by Xuan
- [Insights](https://hackmd.io/@L9ZnGph8Tbaio2GVX_z-EA/ryqt7RKJa) by Robert Yan
- [Wireframe](https://www.figma.com/file/ZKPJMv8vwn3rWzoHa4bKki/Component-Discovery?type=design&node-id=0-1&mode=design&t=Cx6xv42Q6Hw5b3XP-0) by Tiffany 
- [NEARCon Design](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=975%3A2&type=design&node-id=975-5073&viewport=511%2C1088%2C1&t=SM79BySZGdDUYW4R-1&scaling=min-zoom&starting-point-node-id=975%3A5290&show-proto-sidebar=1)

```[tasklist]
### MVP
- [ ] https://github.com/near/data-platform/issues/2
- [ ] https://github.com/near/data-analytics/issues/17
```

```[tasklist]
### Next Ver.
- [ ] https://github.com/near/data-platform/issues/51
- [ ] https://github.com/near/data-platform/issues/4
- [ ] https://github.com/near/data-platform/issues/6
- [ ] https://github.com/near/near-search/issues/46
- [ ] https://github.com/near/near-discovery/issues/622
```
