### ISSUE TITLE
🔰 [Initiative] Component Activity Feed (in Main Feed)

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/Pagoda-Roadmap#65]
### Description
Improve App Discovery experience with a focus on increasing developer conversion and community engagement. 

![Image](https://github.com/near/Pagoda-Roadmap/assets/35774078/053c81a5-4bf2-48b2-9d0a-7632e3e59fac)

### User Flow
**Developer Just Joined**
1. The developer A lands on near.org and sees a feed in the page with a tab says "components"
2. A land on the tab and sees a scrolling feed of components that looks well made and ready to use
3. A scroll for a while and is prompted to follow other developers who have a track record of being actively contributing with high quality works and influential
4. After A followed some developers prompted, they start to see the feed gets additional information about the components that the developers they follow have published, in addition to some activities such as B liked X component, C saved Y component
5. A continue to explore the feed, like and save some components they find interesting and helpful

**Developer Re-Engage**
1. After developer A explore the feed, follow, like and save some components, A has to leave to deal with some matters
2. After a few days, A gets a notification(could be email) prompting A that A have saved XYZ components and there are new components published by the developers A follows
3. A recalls the powerful experience of BOS and gets back to near.org to build

**Publish Component** <by Connect team>
1. Developer A is ready to publish a component and see an option to add descriptions and others to form it into a post
2. A clicks into the option and drafts the post and hit publish
3. The post shows up in the feed

**Privacy Setting** <TBD>
1. Developer A just finishes a component but decides that they does not want this component to be seen in the feed
2. Developer sees an option for it in the publishing flow and selects it

### Impact
- Engagement with more components discoverable
- Increase the developer network effect by providing more ways to engage with Devs you followed and center around their works
- Combined with reputation to further enhance engagement

### Dependencies 
- Developer Reputation System as additional data to rank and complete developer discovery algo
- Component embed in post publishing flow

### Resources
(Relevant documentation, Figma links, and other reference material)
- Item 1
- Item 2
- Item 3

```[tasklist]
### MVP
- [ ] https://github.com/near/data-platform/issues/3
- [ ] https://github.com/near/data-platform/issues/19
- [ ] https://github.com/near/data-platform/issues/13
```

```[tasklist]
### Next Ver.
- [ ] https://github.com/near/data-platform/issues/20
- [ ] https://github.com/near/data-platform/issues/16
```

**Comment by xuan-ytr** [comment]
@TiffanyGYJ reposting some questions here from related data-platform ticket: https://github.com/near/data-platform/issues/19#issuecomment-1828547940

**Comment by xuan-ytr** [comment]
[Design in review](https://www.figma.com/proto/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?page-id=1150%3A592&type=design&node-id=1220-13477&viewport=-1683%2C475%2C0.5&t=LbrVdfemqDCnR10A-1&scaling=scale-down-width&mode=design).

cc @TiffanyGYJ @Kevin101Zhang @sarahmills
