### ISSUE TITLE
🔰 [Initiative] App Library V2 - Extensible + Rich Data + Curation & Update Pipeline

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/Pagoda-Roadmap#66]
### Description

1. Making App Library Extensible to include
    - Cross-chain Apps
    - Ecosystem projects such as Sweat, Paras, Calimero

2. Enable richer data for Apps to include more engagement and impression data

3. Currently this list is categorized and updated manually, however, it is not sustainable nor autonomous.
We want to have 
      - algorithm to analyze Apps when they are published and categorize them
      - algorithm to rank the order of apps by data and metrics such as views, usages, likes etc. and this will be powering "feature" section

### Resources
(Relevant documentation, Figma links, and other reference material)
- Item 1
- Item 2
- Item 3

```[tasklist]
### NEARCon Launch
- [ ] https://github.com/near/data-platform/issues/10
```

```[tasklist]
### Phase 2
- [ ] https://github.com/near/data-platform/issues/9
- [ ] https://github.com/near/data-platform/issues/18
- [ ] https://github.com/near/data-platform/issues/17
```

**Comment by TiffanyGYJ** [comment]
Add a EVM Section in Develop
