### ISSUE TITLE
🔰 [Initiative] Developer Profiles

### ISSUE THREAD

**Issue by ravigautham** [near/Pagoda-Roadmap#74]
### Description
Overhaul of current profile experience on near.org to cater more towards developers. Giving developers the ability to feature components and applications that they have built and showcase their reputation in the NEAR community.

### Resources

```[tasklist]
### Related Epics
- [ ] Migrate/Integrate Github Reputation
- [ ] Commit graph
- [ ] Customize and Save (static vs. dynamic)
- [ ] Buy me a coffee / sponsor
- [ ] Sponsor lists
```
