### ISSUE TITLE
🔰 [Initiative] Developer Onboarding

### ISSUE THREAD

**Issue by thisisjoshford** [near/Pagoda-Roadmap#82]
### Description
The current onboarding flow has some broken functionality and, ultimately, is not an engaging experience that showcases the platform's value. It also focuses solely on how to use the IDE rather than the near.org platform.

The epics listed at the bottom will focus on incremental improvements by selecting some of the ideal state tasks to work on. 

---

### Goal

Our ideal onboarding flow should help users gain a solid understanding of what BOS is, how to use it, how to find the resources they need, and most importantly **what value it brings**. 

As outlined in the [onboarding section](https://docs.google.com/document/d/1lrWCQRnycA7GG6ikQHqyXWCTEVJOzs8FjKKsKs4QpxQ/edit#heading=h.mc1pavb79gty) of Developer Experience Essentials, the ultimate goal is to reduce the time it takes someone to go from knowing nothing to "Wow, I see the value in this!" (aka “zero - aha!”)

---

### Ideal State

High visibility and easily discoverable:
- [ ] Overview of BOS
- [ ] Docs
- [ ] Featured components (examples)
- [ ] View source of any component
- [ ] View platform updates & features (release notes)
- [ ] Where to get support
- [ ] Where to provide feedback
- [ ] Profile Build-> IDE Onboarding

 IDE Onboarding:
- [ ] Intuitive UI w/ tooltip notes
- [ ] How to customize existing components
- [ ] How to create a component
- [ ] modify profile component
- [ ] fork and publish changes
- [ ] Show new component created
- [ ] Show commit graph
- [ ] Show badge 
- [ ] Explain dev reputation and how to enhance
- [ ] Clear next steps
  - [ ] Show the next task/achievement, allowing access to Devhub gigs
  - [ ] DevHub gigs community
  - [ ] Featured examples 
  - [ ] Developing locally

---

### Resources
- [Dev Onboarding MVP Design](https://www.figma.com/file/wiHosmPTJOf2pUeplEnh0b/Developer-Onboarding-MVP)
- [Dev Growth Flywheel](https://www.figma.com/file/Gh2oEtmdiQXIT1YiewRRKK/Dev-Growth-Flywheel?type=whiteboard&node-id=0-1&t=VKBgwTU30qiVQhra-0)

---

### Execution Plan
- v0.1 -> Essential resources visible & accessible paired with IDE UI redesign in preparation for next phase
- v0.2 -> Tutorial-based onboarding w/ interactive documentation
- v0.3 -> Adjustments based on feedback from v0.1 & v0.2+ additional interactive tutorial options.

```[tasklist]
### Related Epics
- [ ] https://github.com/near/near-discovery/issues/657
- [ ] https://github.com/near/docs/issues/1766
```
