### ISSUE TITLE
🔰 [Initiative] NEAR Public Explorer Database Sunsetting

### ISSUE THREAD

**Issue by charleslavon** [near/Pagoda-Roadmap#83]
### Description
Pagoda made a decision to sunset NEAR Explorer as a product. This means that explorer.near.org (and explorer.testnet.near.org) will become a landing page with a list of available alternatives, and the existing explorer.near.org will be hosted under a new domain name and will be transitioned to the community through DevHub. Read more here: https://near.social/devgovgigs.near/widget/gigs-board.pages.Post?id=635.

### What exactly is being shut down?
You will lose access to databases with these URLs, or other Replicas you might have been given access to:
testnet.db.explorer.indexer.near.dev/testnet_explorer
mainnet.db.explorer.indexer.near.dev/mainnet_explorer

There is no plan to shut down any other data products, such as [NEAR Lake](https://docs.near.org/concepts/advanced/near-lake-framework) or [EnhancedAPI](https://www.pagoda.co/enhanced-api) at the moment.
#### What is the timeline?
Postgres users will lose access to data on the 30th of November, Thursday (12:00 pm Pacific Time Zone). Please migrate to one of the options listed below instead.
#### What does this mean for me?
If you are using the public Postgres Explorer Database, you will need to migrate to other solutions, depending on your use-case. You should start planning for it right now and reach out to this Telegram group to get help: https://nearbuilders.com/tg-data.

#### We will have to accommodate this change across the following features
- [] contract-helper's 3 indexer-for-explorer-mainnnet-readonly-wallet-replica* instances [here](https://console.cloud.google.com/sql/instances?project=near-core))?
- [] pagoda console has UI components which reference explorer DBs
- [] mynearwallet still uses these for recent transactions, etc
- [] @pkudinov have I missed any other areas?

```[tasklist]
### Related Epics
- [ ] https://github.com/near/github-project-test/issues/1
- [ ] https://github.com/near/github-project-test/issues/2
- [ ] https://github.com/near/github-project-test/issues/3
```
